"""create initial F1 schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-21

Hand-written (not autogenerated) so every column type, nullability, and
index exactly matches the SQLAlchemy models in app/models/. Tables are
created in dependency order: lookup/independent tables first, then
races (which everything else hangs off), then the per-race detail
tables last.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Independent / lookup tables ---
    op.create_table(
        "seasons",
        sa.Column("year", sa.Integer(), primary_key=True),
        sa.Column("url", sa.String(length=255), nullable=True),
    )

    op.create_table(
        "circuits",
        sa.Column("circuit_id", sa.Integer(), primary_key=True),
        sa.Column("circuit_ref", sa.String(length=100), nullable=False, unique=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("lat", sa.Numeric(9, 6), nullable=True),
        sa.Column("lng", sa.Numeric(9, 6), nullable=True),
        sa.Column("alt", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
    )
    op.create_index("ix_circuits_country", "circuits", ["country"])

    op.create_table(
        "status",
        sa.Column("status_id", sa.Integer(), primary_key=True),
        sa.Column("status", sa.String(length=100), nullable=False, unique=True),
    )

    op.create_table(
        "drivers",
        sa.Column("driver_id", sa.Integer(), primary_key=True),
        sa.Column("driver_ref", sa.String(length=100), nullable=False, unique=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=3), nullable=True),
        sa.Column("forename", sa.String(length=100), nullable=False),
        sa.Column("surname", sa.String(length=100), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
    )
    op.create_index("ix_drivers_nationality", "drivers", ["nationality"])
    op.create_index("ix_drivers_surname", "drivers", ["surname"])

    op.create_table(
        "constructors",
        sa.Column("constructor_id", sa.Integer(), primary_key=True),
        sa.Column("constructor_ref", sa.String(length=100), nullable=False, unique=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
    )
    op.create_index("ix_constructors_nationality", "constructors", ["nationality"])

    # --- Races (depends on seasons, circuits) ---
    op.create_table(
        "races",
        sa.Column("race_id", sa.Integer(), primary_key=True),
        sa.Column("year", sa.Integer(), sa.ForeignKey("seasons.year"), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column(
            "circuit_id", sa.Integer(), sa.ForeignKey("circuits.circuit_id"), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("time", sa.Time(), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("fp1_date", sa.Date(), nullable=True),
        sa.Column("fp1_time", sa.Time(), nullable=True),
        sa.Column("fp2_date", sa.Date(), nullable=True),
        sa.Column("fp2_time", sa.Time(), nullable=True),
        sa.Column("fp3_date", sa.Date(), nullable=True),
        sa.Column("fp3_time", sa.Time(), nullable=True),
        sa.Column("quali_date", sa.Date(), nullable=True),
        sa.Column("quali_time", sa.Time(), nullable=True),
        sa.Column("sprint_date", sa.Date(), nullable=True),
        sa.Column("sprint_time", sa.Time(), nullable=True),
    )
    op.create_index("ix_races_year", "races", ["year"])
    op.create_index("ix_races_circuit_id", "races", ["circuit_id"])
    op.create_index("ix_races_year_round", "races", ["year", "round"], unique=True)

    # --- Results (depends on races, drivers, constructors, status) ---
    op.create_table(
        "results",
        sa.Column("result_id", sa.Integer(), primary_key=True),
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), nullable=False),
        sa.Column("driver_id", sa.Integer(), sa.ForeignKey("drivers.driver_id"), nullable=False),
        sa.Column(
            "constructor_id",
            sa.Integer(),
            sa.ForeignKey("constructors.constructor_id"),
            nullable=False,
        ),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("grid", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("position_text", sa.String(length=10), nullable=True),
        sa.Column("position_order", sa.Integer(), nullable=False),
        sa.Column("points", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("laps", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("time", sa.String(length=20), nullable=True),
        sa.Column("milliseconds", sa.Integer(), nullable=True),
        sa.Column("fastest_lap", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("fastest_lap_time", sa.String(length=20), nullable=True),
        sa.Column("fastest_lap_speed", sa.Numeric(7, 3), nullable=True),
        sa.Column("status_id", sa.Integer(), sa.ForeignKey("status.status_id"), nullable=False),
    )
    op.create_index("ix_results_race_id", "results", ["race_id"])
    op.create_index("ix_results_driver_id", "results", ["driver_id"])
    op.create_index("ix_results_constructor_id", "results", ["constructor_id"])
    op.create_index("ix_results_status_id", "results", ["status_id"])
    op.create_index("ix_results_driver_race", "results", ["driver_id", "race_id"])

    # --- Lap times (composite PK: race_id, driver_id, lap) ---
    op.create_table(
        "lap_times",
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), primary_key=True),
        sa.Column(
            "driver_id", sa.Integer(), sa.ForeignKey("drivers.driver_id"), primary_key=True
        ),
        sa.Column("lap", sa.Integer(), primary_key=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("time", sa.String(length=20), nullable=True),
        sa.Column("milliseconds", sa.Integer(), nullable=True),
    )
    op.create_index("ix_lap_times_driver_id", "lap_times", ["driver_id"])

    # --- Pit stops (composite PK: race_id, driver_id, stop) ---
    op.create_table(
        "pit_stops",
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), primary_key=True),
        sa.Column(
            "driver_id", sa.Integer(), sa.ForeignKey("drivers.driver_id"), primary_key=True
        ),
        sa.Column("stop", sa.Integer(), primary_key=True),
        sa.Column("lap", sa.Integer(), nullable=False),
        sa.Column("time", sa.String(length=20), nullable=True),
        sa.Column("duration", sa.String(length=20), nullable=True),
        sa.Column("milliseconds", sa.Integer(), nullable=True),
    )
    op.create_index("ix_pit_stops_driver_id", "pit_stops", ["driver_id"])

    # --- Qualifying (depends on races, drivers, constructors) ---
    op.create_table(
        "qualifying",
        sa.Column("qualify_id", sa.Integer(), primary_key=True),
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), nullable=False),
        sa.Column("driver_id", sa.Integer(), sa.ForeignKey("drivers.driver_id"), nullable=False),
        sa.Column(
            "constructor_id",
            sa.Integer(),
            sa.ForeignKey("constructors.constructor_id"),
            nullable=False,
        ),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("q1", sa.String(length=20), nullable=True),
        sa.Column("q2", sa.String(length=20), nullable=True),
        sa.Column("q3", sa.String(length=20), nullable=True),
    )
    op.create_index("ix_qualifying_race_id", "qualifying", ["race_id"])
    op.create_index("ix_qualifying_driver_id", "qualifying", ["driver_id"])
    op.create_index("ix_qualifying_constructor_id", "qualifying", ["constructor_id"])

    # --- Driver standings (depends on races, drivers) ---
    op.create_table(
        "driver_standings",
        sa.Column("driver_standings_id", sa.Integer(), primary_key=True),
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), nullable=False),
        sa.Column("driver_id", sa.Integer(), sa.ForeignKey("drivers.driver_id"), nullable=False),
        sa.Column("points", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("position_text", sa.String(length=10), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_driver_standings_race_id", "driver_standings", ["race_id"])
    op.create_index("ix_driver_standings_driver_id", "driver_standings", ["driver_id"])
    op.create_index(
        "ix_driver_standings_driver_race", "driver_standings", ["driver_id", "race_id"]
    )

    # --- Constructor standings (depends on races, constructors) ---
    op.create_table(
        "constructor_standings",
        sa.Column("constructor_standings_id", sa.Integer(), primary_key=True),
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), nullable=False),
        sa.Column(
            "constructor_id",
            sa.Integer(),
            sa.ForeignKey("constructors.constructor_id"),
            nullable=False,
        ),
        sa.Column("points", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("position_text", sa.String(length=10), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_constructor_standings_race_id", "constructor_standings", ["race_id"])
    op.create_index(
        "ix_constructor_standings_constructor_id", "constructor_standings", ["constructor_id"]
    )
    op.create_index(
        "ix_constructor_standings_constructor_race",
        "constructor_standings",
        ["constructor_id", "race_id"],
    )

    # --- Constructor results (depends on races, constructors) ---
    op.create_table(
        "constructor_results",
        sa.Column("constructor_results_id", sa.Integer(), primary_key=True),
        sa.Column("race_id", sa.Integer(), sa.ForeignKey("races.race_id"), nullable=False),
        sa.Column(
            "constructor_id",
            sa.Integer(),
            sa.ForeignKey("constructors.constructor_id"),
            nullable=False,
        ),
        sa.Column("points", sa.Numeric(6, 2), nullable=False, server_default="0"),
        sa.Column("status", sa.String(length=100), nullable=True),
    )
    op.create_index("ix_constructor_results_race_id", "constructor_results", ["race_id"])
    op.create_index(
        "ix_constructor_results_constructor_id", "constructor_results", ["constructor_id"]
    )


def downgrade() -> None:
    # Drop in reverse dependency order
    op.drop_table("constructor_results")
    op.drop_table("constructor_standings")
    op.drop_table("driver_standings")
    op.drop_table("qualifying")
    op.drop_table("pit_stops")
    op.drop_table("lap_times")
    op.drop_table("results")
    op.drop_table("races")
    op.drop_table("constructors")
    op.drop_table("drivers")
    op.drop_table("status")
    op.drop_table("circuits")
    op.drop_table("seasons")
